[font]
size = 11.0
normal = {family = "Mononoki Nerd Font",style = "Regular"}
bold = {family = "Mononoki Nerd Font",style = "Bold"}
italic  = {family = "Mononoki Nerd Font",style = "Italic"}
bold_italic = {family = "Mononoki Nerd Font",style = "Bold Italic"}
offset = {x = 1,y = 0}

[colors]

[colors.primary]
background = "#0b0b0f"
foreground = "#c0caf5"

[colors.cursor]
text = "CellBackground"
cursor = "#528bff"

[colors.selection]
text = "CellForeground"
background = "#3e4451"

[colors.normal]
black = "#1c1f24"
red = "#f7768e"
green = "#9ece6a"
yellow = "#f0a02e"
blue = "#0096FF"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#545c7e"
red = "#ff007c"
green = "#73daca"
yellow = "#ff9e64"
blue = "#2ac3de"
magenta = "#9d7cd8"
cyan = "#b4f9f8"
white = "#a9b1d6"

[window]
opacity = 0.93
padding = {x=0, y=0}
dynamic_padding=false
