[font]
size = 11.0

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.offset]
x = 1
y = 0

[colors]
[colors.primary]
background = "#0b0b0f"
foreground = "#bbc2cf"

[colors.cursor]
text = "CellBackground"
cursor = "#528bff"

[colors.selection]
text = "CellForeground"
background = "#3e4451"

[colors.normal]
black = "#1c1f24"
red = "#ff6c6b"
green = "#98be65"
yellow = "#da8548"
blue = "#51afef"
magenta = "#c678dd"
cyan = "#5699af"
white = "#abb2bf"

[colors.bright]
black = "#5b6268"
red = "#da8548"
green = "#4db5bd"
yellow = "#ecbe7b"
blue = "#3071db"
magenta = "#a9a1e1"
cyan = "#46d9ff"
white = "#dfdfdf"

[window]
opacity=0.93
blur= true
decorations="Buttonless"

